#!/usr/bin/bash

# variables
scripts=~/.config/.scripts

# gsettings
#gsettings set org.gnome.desktop.interface gtk-theme 'Tokyonight-Dark-BL-LB'
#gsettings set org.gnome.desktop.interface font-name 'SF Pro Text 9'
#gsettings set org.gnome.desktop.interface icon-theme 'Tokyonight-Moon'
#gsettings set org.gnome.desktop.interface cursor-theme 'Sweet-cursors'
#

# notification daemon
swaync &

# lock/suspend when idle
hypridle &

# waybar
$scripts/launch_waybar &
# $scripts/dynamic &

# music daemon
# mpd &
# g4music &

# wallpaper
$scripts/wall ~/.config/hypr/wallpapers/1.jpg &
hyprpaper
# effects
# $scripts/tools/rgb &

# audio
gentoo-pipewire-launcher &

=======
# Applets
$scripts/appindicator.py &
blueman-applet &
nm-applet --indicator &\

# other
hyprctl setcursor Sweet-cursors 30 
wl-paste --watch cliphist store &
notify-send -a aurora "hello $(whoami)" &
libinput-gestures-setup start &

# sleep 1
# mpd-mpris &
# hyprctl dispatch movetoworkspacesilent 2,com.github.neithern.g4music


# sleep 1
# killall xdg-desktop-portal-hyprland
# killall xdg-desktop-portal
# /usr/lib/xdg-desktop-portal-hyprland &
# sleep 2
# /usr/lib/xdg-desktop-portal &
