preload = /home/laurenz/.config/hypr/wallpapers/1.jpg
preload = /home/laurenz/.config/hypr/wallpapers/voyager-tophx-panda-cover.jpeg
preload = /home/laurenz/.config/hypr/wallpapers/longjump.jpg
wallpaper = DP-2,/home/laurenz/.config/hypr/wallpapers/1.jpg
wallpaper = DP-1,/home/laurenz/.config/hypr/wallpapers/1.jpg

#wallpaper = DP-1, /home/laurenz/.config/hypr/wallpapers/voyager-tophx-panda-cover.jpeg
wallpaper = HDMI-A-1, /home/laurenz/.config/hypr/wallpapers/1.jpg
